project:
  type: website
  output-dir: docs
  preview:
    port: 5896
    browser: true
  render:
    - "*.qmd"
  resources:
    - "content/"
    - "css"
    - "static/"

website:
  title: "laurenchenarides.com"
  description: "The personal website of Lauren Chenarides"
  image: images/photo.png
  site-url: https://www.laurenchenarides.com
  repo-url: https://github.com/laurenchenarides/website
  search:
    location: navbar
    type: overlay
  back-to-top-navigation: false
  open-graph:
    site-name: laurenchenarides.com
  navbar:
    right:
      - text: "About"
        href: bio.qmd
      # - text: "Lab"
      #   href: lab.qmd
      # - text: "Research"
      #   href: research.qmd
      # - text: "Teaching"
      #   href: teaching.qmd
      # - text: "Projects"
      #   href: projects.qmd
      # - text: "Workshops"
      #   href: workshops.qmd
  page-footer:
    center:
      - text: "<a href='www.laurenchenarides.com/cv.html'>CV</a> &nbsp;<a href='https://github.com/laurenchenarides' target='blank'><i class='bi bi-github'></i></a> &nbsp;<a href='https://www.linkedin.com/in/laurenchenarides/' target='blank'><i class='bi bi-linkedin'></i></a> &nbsp;<a href='https://scholar.google.com/citations?user=07RAgEQAAAAJ&hl=en' target='blank'><i class='ai ai-google-scholar fa-lg'></i></a> &nbsp;<a href='https://orcid.org/my-orcid?orcid=0000-0001-8983-9694' target='blank'><i class='ai ai-orcid fa-lg'></i></a><br>Site made with <i class='bi bi-heart-fill'></i>, <a href='https://github.com/laurenchenarides/personal_website' target='_blank'><i class='bi bi-git'></i></a>, and <a href='https://quarto.org/' target='_blank'><img src='https://quarto.org/favicon.png' width=12> quarto</a><br>© 2025 Lauren Chenarides"

format:
  html:
    theme: [default, css/theme.scss]
    anchor-sections: true
    smooth-scroll: true
    link-external-newwindow: true
    link-external-icon: false
    # This is to include fontawesome and academic icons in the headers:
    include-in-header: "_includes/header.html"
